[package]
name = "rc-zip"
version = "0.0.1"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"
description = "zip reading and writing"
repository = "https://github.com/rust-compress/rc-zip"
readme = "README.md"
license = "MIT"

keywords = ["zip", "unzip"]
categories = ["compression"]

[badges]
travis-ci = { repository = "rust-compress/rc-zip" }
maintenance = { status = "experimental" }

[profile.dev]
opt-level = 0
debug = true

[profile.release]
debug = true

[dependencies]
nom = "5.0.0"
positioned-io = "0.2.2"
pretty-hex = "0.1.0"
hex_fmt = "0.3.0"
circular = "0.3.0"
chrono = "0.4.7"
chardet = "0.2.4"
encoding_rs = "0.8.17"
codepage-437 = "0.1.0"
log = "0.4.7"
libflate = "0.1.25"
crc32fast = "1.2.0"

[dev-dependencies]
color-backtrace = "0.2.2"
env_logger = "0.6.2"

[workspace]
members = [ ".", "samples/jean" ]
default-members = [ ".", "samples/jean" ]

