stages:
  - build
  - deploy

build:linux:
  stage: build
  tags: ["docker-capsule-64"]
  script:
    - xvfb-run -- npm run build -- --os linux --arch x86_64 --test-runtime electron
  artifacts:
    expire_in: 1 week
    paths: ["artifacts"]

build:darwin:
  stage: build
  tags: ["darwin"]
  script:
    - npm run build -- --os darwin --arch x86_64 --test-runtime electron
  artifacts:
    expire_in: 1 week
    paths: ["artifacts"]

build:windows:
  stage: build
  tags: ["windows"]
  script:
    - npm run build -- --os windows --arch x86_64 --test-runtime electron
    - npm run build -- --os windows --arch i686 --test-runtime electron
  artifacts:
    expire_in: 1 week
    paths: ["artifacts"]
