[package]
name = "valet"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[lib]
crate-type = ["cdylib"]

[dependencies]
libbutler = { path = "./libbutler" }
napi = { path = "./napi" }
log = "0.4.8"
pretty_env_logger = "0.4.0"

[target.'cfg(windows)'.dependencies]
napi_stub = { path = "./napi_stub" }
