[package]
name = "valet"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[lib]
crate-type = ["cdylib"]

[dependencies]
libbutler = { path = "./libbutler" }
napi = { path = "./napi" }

[target.'cfg(windows)'.dependencies]
mingw_compat = { path = "./mingw_compat" }
napi_stub = { path = "./napi_stub" }
