[package]
name = "wallet"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nj-sys = "1.0.0"

[build-dependencies]
cc = "1.0.50"
