[package]
name = "selfupdate"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
thiserror = "1.0.20"
serde = { version = "1.0.114", features = ["derive"] }
once_cell = "1.4.0"
httpkit = { path = "../httpkit" }