[package]
name = "selfupdate-cmd"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
selfupdate = { path = ".." }
argh = "0.1.3"
tokio = { version = "0.2.22", features = ["full"] }
pretty_env_logger = "0.4.0"
log = "0.4.11"

