[package]
name = "libbutler"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
napi = { path = "../napi" }

[build-dependencies]
mingw_setup = { path = "../mingw_setup" }
